apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: charlie
  name: charlie
spec:
  replicas: 1
  selector:
    app: charlie
  template:
    metadata:
      labels:
        app: charlie
    spec:
      containers:
      - image: gcr.io/faceit-ltd/charlie:latest
        imagePullPolicy: Always
        name: charlie
        ports:
        - containerPort: 9921
          protocol: TCP
          name: web
        - containerPort: 9923
          protocol: TCP
          name: api
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
