apiVersion: v1
kind: Service
metadata:
  labels:
    app: charlie
    tier: internal
  name: charlie
spec:
  clusterIP: 10.0.214.136
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: web
  - port: 9922
    protocol: TCP
    targetPort: 9922
    name: api
  selector:
    app: charlie
  sessionAffinity: None
  type: ClusterIP
