apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: torhost
  name: torhost
spec:
  replicas: 1
  selector:
    app: torhost
  template:
    metadata:
      labels:
        app: torhost
    spec:
      volumes:
      - name: hs-config
        secret:
          secretName: "hs-config"
      containers:
      - image: gcr.io/faceit-ltd/torhost:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: hs-config
          readOnly: true
          mountPath: /etc/hidden_service
        name: torhost
      dnsPolicy: ClusterFirst
      restartPolicy: Always
