apiVersion: v1
kind: Service
metadata:
  labels:
    app: torhost
    tier: internal
  name: torhost
spec:
  clusterIP: 10.0.252.9
  ports:
  - port: 9050
    protocol: TCP
    targetPort: 9050
  selector:
    app: torhost
  sessionAffinity: None
  type: ClusterIP
