# Build {MODULE_NAME}
file(GLOB_RECURSE {MODULE_NAME}_SRC "${CHARLIE_MODULE_PATH}/{MODULE_NAME}/*.cpp")
add_library({MODULE_NAME} SHARED ${{MODULE_NAME}_SRC} ${CHARLIE_MODULE_SRC})
set_target_properties({MODULE_NAME} PROPERTIES COMPILE_FLAGS "${MODULE_FLAGS} -DCHARLIE_MODULE_NAME='\"{MODULE_NAME_UC}\"'")
set_target_properties({MODULE_NAME} PROPERTIES LINK_FLAGS     ${STATIC_LIBC_ARGS})
target_link_libraries({MODULE_NAME} ${CHARLIE_MODULE_LINK} -Wl,-Bstatic ${PROTOBUF_LITE_LIBRARIES})
add_custom_command(TARGET {MODULE_NAME} POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:{MODULE_NAME}> ${CMAKE_SHARED_LIBRARY_PREFIX}{MODULE_ID}${CMAKE_SHARED_LIBRARY_SUFFIX}
)
