# Build {MODULE_NAME} (server version)
file(GLOB_RECURSE s_{MODULE_NAME}_SRC "${CHARLIE_SERVER_MODULE_PATH}/{MODULE_NAME}/*.cpp" "{MODULE_NAME}.pb.redacted.cc")
add_library(s_{MODULE_NAME} SHARED ${s_{MODULE_NAME}_SRC} ${CHARLIE_MODULE_SRC}
  "{MODULE_NAME}.pb.redacted.cc")
set_target_properties(s_{MODULE_NAME} PROPERTIES COMPILE_FLAGS "${MODULE_FLAGS} -DCHARLIE_MODULE_NAME='\"{MODULE_NAME}\"'")
set_target_properties(s_{MODULE_NAME} PROPERTIES LINK_FLAGS     ${STATIC_LIBC_ARGS})
target_link_libraries(s_{MODULE_NAME} -Wl,-Bstatic ${PROTOBUF_LITE_LIBRARIES})
add_custom_command(TARGET {MODULE_NAME} POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:s_{MODULE_NAME}> ${CMAKE_BINARY_DIR}/server_modules/${CMAKE_SHARED_LIBRARY_PREFIX}{MODULE_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX}
)
